name: DeployRinkeby
on:
  push:
    branches:
      - rinkeby

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g @graphprotocol/graph-cli
      - run: graph codegen
      - run: graph auth --product hosted-service 8725b84630924b0f981a40082bd02409
        env:
          API_KEY: ${{ secrets.GRAPH_API_KEY }}
      - run: graph deploy --product hosted-service  posix4e/humanrinkeby
